name: Build and Release Eye-Break Timer

on:
  push:
    branches: [ main ]
  # Optionally trigger on pull requests
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Build Electron app
        run: |
          npm run build
          
      # For Windows
      - name: Package Windows app
        if: matrix.os == 'windows-latest'
        run: |
          npm run make
          
      # For macOS
      - name: Package macOS app
        if: matrix.os == 'macos-latest'
        run: |
          npm run make
          
      - name: List build output files
        run: |
          ls -R out/ || echo "out/ directory not found"
          ls -R dist/ || echo "dist/ directory not found"
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eye-break-timer-${{ matrix.os }}
          path: |
            out/make/**/*.exe
            out/make/**/*.dmg
            out/make/**/*.zip
            dist/**/*.exe
            dist/**/*.dmg
            dist/**/*.zip
            
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: |
            out/make/**/*.exe
            out/make/**/*.dmg
            out/make/**/*.zip
            dist/**/*.exe
            dist/**/*.dmg
            dist/**/*.zip
          token: ${{ secrets.GITHUB_TOKEN }} 